---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - src: git@github.com:andrewchikin/lighthouse-role.git
    scm: git
    version: "1.0.0"
    name: lighthouse 

  - src: git@github.com:andrewchikin/vector-role.git
    scm: git
    version: "1.0.0"
    name: vector 